apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-httpd-dep
  labels:
    app: sample    
spec:
  selector: 
    matchLabels:
      app: sample
  template:
    metadata:
      name: httpd-pod
      labels:
        app: sample
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
  replicas: 2