apiVersion: v1
kind: Service
metadata:
  name: sample-httpd-service
  labels:
    app: sample
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: sample